[project]
name = "ublue-rebase-helper"
version = "1.1.0"
description = "Implementation of bazzite-rebase-helper for compatibility with custom images"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pytest>=8.4.2", "pytest-mock>=3.15.1", "slipcover>=1.0.17"]
